### ISSUE TITLE
Enter a shell to submit custom arguments to sbcl?

### ISSUE THREAD

**Issue by fosskers** [fukamachi/dockerfiles#98]
Rather than have the container immediately enter the sbcl REPL, I was hoping to run `sbcl --eval "..."` and have it do something simple and then exit. Unfortunately I couldn't figure out how to do this; it would always enter the REPL interactively. 

Do you know how to do what I'm attempting?

**Comment by fukamachi** [comment]
It's the same as `sbcl` command.

```
$ docker run --rm -it fukamachi/sbcl --eval '(print (lisp-implementation-version))' --quit
2.4.4
```

**Comment by fosskers** [comment]
Confirmed. Thank you!
